version: '3.7'
services:
  db:
    image: postgres:15
    container_name: lms_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis:7
    container_name: lms_cache

  lms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lms_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    command:
      - "docker/app.sh"
    ports:
      - 7777:8000

  celery:
    build: .
    container_name: lms_celery
    env_file:
      - .env-non-dev
    command:
      - "docker/celery.sh"
    depends_on:
      - lms

  celery-beat:
    build: .
    container_name: lms_celery_beat
    env_file:
      - .env-non-dev
    command:
       - "docker/celery_beat.sh"
    depends_on:
      - lms