# Generated by Django 4.2.6 on 2023-10-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_payments_lessonsqty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_type_bank',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='payment_type_cash',
        ),
        migrations.AddField(
            model_name='payments',
            name='payment_type',
            field=models.TextField(default=True, verbose_name='способ оплаты: наличные или перевод'),
        ),
    ]
