# Generated by Django 4.2.6 on 2023-10-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_remove_payments_payment_type_bank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество уроков')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='lessons.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity', to='lessons.lesson')),
            ],
            options={
                'verbose_name': 'количество уроков',
                'verbose_name_plural': 'количество уроков',
            },
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Cash', verbose_name='способ оплаты: наличные или перевод'),
        ),
        migrations.DeleteModel(
            name='LessonsQty',
        ),
    ]
