# Generated by Django 4.2.6 on 2023-11-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_course_delete_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='session',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='сессия'),
        ),
    ]
