# Generated by Django 4.2.6 on 2023-11-09 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_payments_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_type',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], default='Bank', verbose_name='способ оплаты: наличные или перевод'),
        ),
    ]
